### ISSUE TITLE
Error: Undefined References

### ISSUE THREAD

**Issue by kukkieman** [Kienyew/MusicTiles#1]
`C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x8f): undefined reference to GetRandomValue' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1ea): undefined reference tolist_append_tail' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x26c): undefined reference to list_pop_node' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x2d2): undefined reference tolist_append_tail' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x4e7): undefined reference to GetRandomValue' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x5bb): undefined reference tolist_append_tail' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x66f): undefined reference to list_pop_node' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x6cd): undefined reference toIsKeyPressed' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x811): undefined reference to list_pop_node' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x8be): undefined reference tolist_pop_node' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x96b): undefined reference to list_pop_node' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xa48): undefined reference toGetRandomValue' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xa50): undefined reference to PlayPianoNote' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xbb6): undefined reference tolist_pop_node' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xc0c): undefined reference to BeginDrawing' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xc27): undefined reference toClearBackground' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xcd4): undefined reference to DrawLineEx' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xd7b): undefined reference toDrawLineEx' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xe31): undefined reference to DrawRectangle' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xf11): undefined reference toDrawRectangle' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0xfb8): undefined reference to DrawText' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1033): undefined reference toDrawText' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1066): undefined reference to TextFormat' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x108f): undefined reference toDrawText' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x10b4): undefined reference to TextFormat' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x10dd): undefined reference toDrawText' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x10e2): undefined reference to EndDrawing' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1148): undefined reference tolist_clear' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1166): undefined reference to list_clear' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x117c): undefined reference toInitAudioDevice' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x1198): undefined reference to InitWindow' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x11a4): undefined reference toSetTargetFPS' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x11ba): undefined reference to WindowShouldClose' <br/>C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x11cb): undefined reference toCloseWindow' 
C:\Users\rishk\AppData\Local\Temp\ccBnYs68.o:main.c:(.text+0x11d0): undefined reference to 'CloseAudioDevice' 
collect2.exe: error: ld returned 1 exit status `

So I cloned your repo and downloaded it. Tried to run main.c but I'm getting these **undefined reference** errors. Can you help?

**Comment by Kienyew** [comment]
Sure thing, currently it can never work in windows (my fault), I'll add windows support soon, thanks!

**Comment by Kienyew** [comment]
@kukkieman I just integrate cmake in this project and tested in Windows 10.  Try it again now :)

**Comment by kukkieman** [comment]
I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.

**Comment by Kienyew** [comment]
> I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.
@kukkieman 

First of course you need to [download cmake](https://cmake.org/download/) itself and install it.
Basically, once you cloned project repository, the procedures is like this:

1. Prepare a directory for all output files: `mkdir build && cd build`
2. Generate a make file (one single script to auto compile and link all codes in the project) by running: `cmake PATH_TO_PROJECT_ROOT`.
3. Execute the generated make file, usually by a program called *make* by running: `make/nmake`

Consult [this guide](https://cmake.org/cmake/help/latest/guide/user-interaction/index.html) or other site like youtube, good luck 😄
There's also a cmake-gui that make it easier to do.

**Comment by kukkieman** [comment]
> 
> 
> > I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.
> > @kukkieman
> 
> First of course you need to [download cmake](https://cmake.org/download/) itself and install it.
> Basically, once you cloned project repository, the procedures is like this:
> 
>     1. Prepare a directory for all output files: `mkdir build && cd build`
> 
>     2. Generate a make file (one single script to auto compile and link all codes in the project) by running: `cmake PATH_TO_PROJECT_ROOT`.
> 
>     3. Execute the generated make file, usually by a program called _make_ by running: `make/nmake`
> 
> 
> Consult [this guide](https://cmake.org/cmake/help/latest/guide/user-interaction/index.html) or other site like youtube, good luck 😄
> There's also a cmake-gui that make it easier to do.

Thanks! That's really helpful of you! I'll let you know what happens once I'm done with this.

**Comment by kukkieman** [comment]
> 
> 
> > > I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.
> > > @kukkieman
> > 
> > 
> > First of course you need to [download cmake](https://cmake.org/download/) itself and install it.
> > Basically, once you cloned project repository, the procedures is like this:
> > ```
> > 1. Prepare a directory for all output files: `mkdir build && cd build`
> > 
> > 2. Generate a make file (one single script to auto compile and link all codes in the project) by running: `cmake PATH_TO_PROJECT_ROOT`.
> > 
> > 3. Execute the generated make file, usually by a program called _make_ by running: `make/nmake`
> > ```
> > 
> > 
> > Consult [this guide](https://cmake.org/cmake/help/latest/guide/user-interaction/index.html) or other site like youtube, good luck 😄
> > There's also a cmake-gui that make it easier to do.
> 
> Thanks! That's really helpful of you! I'll let you know what happens once I'm done with this.

Sorry I'm back after 30 days to annoy you again. So I dreaded using cmd at first and then moved to cmake-gui, which worked like a charm but then came this error- 
`LNK1104	cannot open file 'm.lib'	music_tiles	E:\Development\GitDirectory\MusicTiles\build\LINK	Line 1`

Also, the header file at line 1 is "raylib.h" but the error mentions "m.lib". BTW did you use the 32-bit or the 64-bit version of cmake?

**Comment by Kienyew** [comment]
> 
> 
> > > > I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.
> > > > @kukkieman
> > > 
> > > 
> > > First of course you need to [download cmake](https://cmake.org/download/) itself and install it.
> > > Basically, once you cloned project repository, the procedures is like this:
> > > ```
> > > 1. Prepare a directory for all output files: `mkdir build && cd build`
> > > 
> > > 2. Generate a make file (one single script to auto compile and link all codes in the project) by running: `cmake PATH_TO_PROJECT_ROOT`.
> > > 
> > > 3. Execute the generated make file, usually by a program called _make_ by running: `make/nmake`
> > > ```
> > > 
> > > 
> > > Consult [this guide](https://cmake.org/cmake/help/latest/guide/user-interaction/index.html) or other site like youtube, good luck 😄
> > > There's also a cmake-gui that make it easier to do.
> > 
> > 
> > Thanks! That's really helpful of you! I'll let you know what happens once I'm done with this.
> 
> Sorry I'm back after 30 days to annoy you again. So I dreaded using cmd at first and then moved to cmake-gui, which worked like a charm but then came this error-
> `LNK1104 cannot open file 'm.lib' music_tiles E:\Development\GitDirectory\MusicTiles\build\LINK Line 1`
> 
> Also, the header file at line 1 is "raylib.h" but the error mentions "m.lib". BTW did you use the 32-bit or the 64-bit version of cmake?

Hey, could you try removing this line: 
```
target_link_libraries(${PROJECT_NAME} m)
```

in `CMakeLists.txt` file and rerun ~the cmake~ everything you did and tell me again what is the result, thanks!

**Comment by kukkieman** [comment]
> 
> 
> > > > > I don't have a lot of experience with cmake, so could you explain it to me please? I'm trying to make a program similar to this with added functionality and graphics (in C/C++ itself) for a graded college project.
> > > > > @kukkieman
> > > > 
> > > > 
> > > > First of course you need to [download cmake](https://cmake.org/download/) itself and install it.
> > > > Basically, once you cloned project repository, the procedures is like this:
> > > > ```
> > > > 1. Prepare a directory for all output files: `mkdir build && cd build`
> > > > 
> > > > 2. Generate a make file (one single script to auto compile and link all codes in the project) by running: `cmake PATH_TO_PROJECT_ROOT`.
> > > > 
> > > > 3. Execute the generated make file, usually by a program called _make_ by running: `make/nmake`
> > > > ```
> > > > 
> > > > 
> > > > Consult [this guide](https://cmake.org/cmake/help/latest/guide/user-interaction/index.html) or other site like youtube, good luck 😄
> > > > There's also a cmake-gui that make it easier to do.
> > > 
> > > 
> > > Thanks! That's really helpful of you! I'll let you know what happens once I'm done with this.
> > 
> > 
> > Sorry I'm back after 30 days to annoy you again. So I dreaded using cmd at first and then moved to cmake-gui, which worked like a charm but then came this error-
> > `LNK1104 cannot open file 'm.lib' music_tiles E:\Development\GitDirectory\MusicTiles\build\LINK Line 1`
> > Also, the header file at line 1 is "raylib.h" but the error mentions "m.lib". BTW did you use the 32-bit or the 64-bit version of cmake?
> 
> Hey, could you try removing this line:
> 
> ```
> target_link_libraries(${PROJECT_NAME} m)
> ```
> 
> in `CMakeLists.txt` file and rerun ~the cmake~ everything you did and tell me again what is the result, thanks!

So the error is gone now and this is the build log:

`1>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------

1>Project not selected to build for this solution configuration 

2>------ Skipped Build: Project: PACKAGE, Configuration: Debug Win32 ------

2>Project not selected to build for this solution configuration 

========== Build: 0 succeeded, 0 failed, 6 up-to-date, 2 skipped ==========`

I checked the BUILD ORDER and they are there. I've tried reactivating the project and rebuilding it as well but no luck!

**Comment by Kienyew** [comment]
> So the error is gone now and this is the build log:
> 
> `1>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------
> 
> 1>Project not selected to build for this solution configuration
> 
> 2>------ Skipped Build: Project: PACKAGE, Configuration: Debug Win32 ------
> 
> 2>Project not selected to build for this solution configuration
> 
> ========== Build: 0 succeeded, 0 failed, 6 up-to-date, 2 skipped ==========`
> 
> I checked the BUILD ORDER and they are there. I've tried reactivating the project and rebuilding it as well but no luck!

If you are running on Visual Studio, after the solution generated by cmake, just open the sln file with visual studio and `Build Project`, the binary file `music_tiles.exe` shall be generated, check the build log for the output folder.

**Comment by kukkieman** [comment]
> 
> 
> > So the error is gone now and this is the build log:
> > `1>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------
> > 1>Project not selected to build for this solution configuration
> > 2>------ Skipped Build: Project: PACKAGE, Configuration: Debug Win32 ------
> > 2>Project not selected to build for this solution configuration
> > ========== Build: 0 succeeded, 0 failed, 6 up-to-date, 2 skipped ==========`
> > I checked the BUILD ORDER and they are there. I've tried reactivating the project and rebuilding it as well but no luck!
> 
> If you are running on Visual Studio, after the solution generated by cmake, just open the sln file with visual studio and `Build Project`, the binary file `music_tiles..txt` shall be generated, check the build log for the output folder.

I had been doing this right until the binary file step. I couldn't find any binary file, but I think I got the output folder. After building the solution, inside the build folder there was a Debug folder created, which had a `music_tiles.exe`. So I ran it and it worked like a charm! I guess this is it for now.

So the problem was that I was generating the program using VS Code 2017 (in cmake-gui) and apparently after building the solution, the INSTALL & PACKAGE weren't building. Their output was in the `..\build\Debug\` directory as an executable file `music_tiles.exe`.

Thanks @Kienyew for being so so so helpful! In case I finish this project on time, I'll be sure to mention you in the credits! I think you can close this issue now.

Cheers!

**Comment by Kienyew** [comment]
> > If you are running on Visual Studio, after the solution generated by cmake, just open the sln file with visual studio and `Build Project`, the binary file `music_tiles..txt` shall be generated, check the build log for the output folder.
> 
> I had been doing this right until the binary file step. I couldn't find any binary file, but I think I got the output folder. After building the solution, inside the build folder there was a Debug folder created, which had a `music_tiles.exe`. So I ran it and it worked like a charm! I guess this is it for now.
> 
> So the problem was that I was generating the program using VS Code 2017 (in cmake-gui) and apparently after building the solution, the INSTALL & PACKAGE weren't building. Their output was in the `..\build\Debug\` directory as an executable file `music_tiles.exe`.
> 
> Thanks @Kienyew for being so so so helpful! In case I finish this project on time, I'll be sure to mention you in the credits! I think you can close this issue now.
> 
> Cheers!

Cheers! My project is not originally configured to be compile in visual studio though, glad to hear that you got that done, glad to hear that you got it done. Also sorry for my typo ~`music_tiles..txt`~ which should be `music_tiles.exe` in my last comment.
